sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t hjhj97/docker-react-app -f ./Dockerfile.dev ./

script:
  - docker run -e CI=true hjhj97/docker-react-app npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-754843398724"
  bucket_path: "docker-react-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
